spring.application.name=edu-share

#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.jpa.hibernate.ddl-auto=none

#spring.datasource.url=jdbc:mysql://localhost:3306/edu_share
#spring.datasource.username=root
#spring.datasource.password=
#spring.jpa.hibernate.ddl-auto=validate

spring.datasource.url=jdbc:mysql://edushareproject-duch75662-d72d.i.aivencloud.com:13212/edu_share?useSSL=true&allowPublicKeyRetrieval=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# S? d?ng bi?n môi tr??ng ?? b?o m?t, n?u không có s? l?y giá tr? m?c ??nh sau d?u hai ch?m
spring.datasource.username=${DB_USERNAME:avnadmin}
spring.datasource.password=${DB_PASSWORD}